const kuwaitAreas = [
  {
    title: {
      en: "Capital",
      ar: "العاصمة",
    },
    areas: [
      { ar: "ضاحية عبدالله السالم", en: "Abdullah Al-Salem Suburb" },
      { ar: "العديلية", en: "Adailiya" },
      { ar: "النهضة", en: "Al Nahda" },
      { ar: "حدائق السور", en: "Hadaeq Al-Soor" },
      { ar: "بنيد القار", en: "Bnied Al-Gar" },
      { ar: "الدعية", en: "Al-Daiya" },
      { ar: "الدسمة", en: "Dasma" },
      { ar: "دسمان", en: "Dasman" },
      { ar: "الدوحة", en: "Doha" },
      { ar: "شاليهات الدوحة", en: "Doha Chalets" },
      { ar: "الفيحاء", en: "Al Faiha" },
      { ar: "غرناطه", en: "Granada" },
      { ar: "جابر الأحمد", en: "Jaber Al-Ahmad" },
      { ar: "الجبلة", en: "Al Jibla" },
      { ar: "القيروان", en: "Al-Qairawan" },
      { ar: "كيفان", en: "Kaifan" },
      { ar: "الخالدية", en: "Khaldiya" },
      { ar: "مدينة الكويت", en: "Kuwait City" },
      { ar: "المنصورية", en: "Mansouriya" },
      { ar: "المرقاب", en: "Mirqab" },
      { ar: "المباركية", en: "Mubarakiya" },
      { ar: "مباركيه", en: "Mubarakiya" },
      { ar: "شمال غرب الصليبيخات", en: "Northwest Sulaibikhat" },
      { ar: "النزهة", en: "Nuzha" },
      { ar: "القادسية", en: "Qadsiya" },
      { ar: "قبلة", en: "Qibla" },
      { ar: "قرطبة", en: "Qurtuba" },
      { ar: "الري", en: "Al Rai" },
      { ar: "الروضة", en: "Rawda" },
      { ar: "منطقة الصباح الصحية", en: "Sabah Health District" },
      { ar: "الصالحية", en: "Salhiya" },
      { ar: "الصوابر", en: "Sawaber" },
      { ar: "الشامية", en: "Shamiya" },
      { ar: "شرق", en: "Sharq" },
      { ar: "الشويخ", en: "Shuwaikh" },
      { ar: "ميناء الشويخ", en: "Shuwaikh Port" },
      { ar: "شويخ السكنية", en: "Shuwaikh Residential" },
      { ar: "الصليبيخات", en: "Sulaibikhat" },
      { ar: "السرة", en: "Surra" },
      { ar: "اليرموك", en: "Yarmouk" },
    ],
  },
  {
    title: {
      en: "Hawalli",
      ar: "حولي",
    },
    areas: [
      { ar: "البدع", en: "Al Bida'a" },
      { ar: "الشهداء", en: "Al Shuhada" },
      { ar: "الصديق", en: "Al Siddiq" },
      { ar: "انجفه", en: "Anjafa" },
      { ar: "بيان", en: "Bayan" },
      { ar: "المنطقة الحرة", en: "Free Trade Zone" },
      { ar: "حطين", en: "Hittin" },
      { ar: "حولي", en: "Hawalli" },
      { ar: "الجابرية", en: "Jabriya" },
      { ar: "ميدان حولي", en: "Maidan Hawalli" },
      { ar: "منطقة الوزارات", en: "Ministries Zone" },
      { ar: "مشرف", en: "Mishref" },
      {
        ar: "ضاحية مبارك العبدالله (غرب مشرف)",
        en: "Mubarak Al-Abdullah Suburb (West Mishref)",
      },
      { ar: "النقرة", en: "Al Nugra" },
      { ar: "الرميثية", en: "Rumaithiya" },
      { ar: "السلام", en: "Al Salam" },
      { ar: "السالمية", en: "Salmiya" },
      { ar: "سلوى", en: "Salwa" },
      { ar: "الشعب", en: "Al Shaab" },
      { ar: "جنوب السرة", en: "South Surra" },
      { ar: "الزهراء", en: "Al Zahra" },
    ],
  },
  {
    title: {
      en: "Mubarak al-Kabeer",
      ar: "مبارك الكبير",
    },
    areas: [
      { ar: "ابو فطيرة", en: "Abu Futaira" },
      { ar: "أبو الحصانية", en: "Abu Al Hasaniya" },
      { ar: "المطار", en: "Al Matar" },
      { ar: "العدان", en: "Al Adan" },
      { ar: "المسايل", en: "Al Masayel" },
      { ar: "فنيطيس", en: "Fnaitees" },
      { ar: "المسيلة", en: "Al Messila" },
      { ar: "مبارك الكبير", en: "Mubarak Al-Kabeer" },
      { ar: "القصور", en: "Al Qusoor" },
      { ar: "القرين", en: "Al Qurain" },
      { ar: "صباح السالم", en: "Sabah Al-Salem" },
      { ar: "صبحان", en: "Subhan" },
      { ar: "ابو فطيره الحرفيه", en: "Abu Futaira Industrial" },
    ],
  },
  {
    title: {
      en: "Ahmadi",
      ar: "الأحمدي",
    },
    areas: [
      { ar: "ابو حليفة", en: "Abu Halifa" },
      { ar: "الظهر", en: "Al-Dhahr" },
      { ar: "الأحمدي", en: "Al Ahmadi" },
      { ar: "علي صباح السالم", en: "Ali Sabah Al-Salem" },
      { ar: "شرق الأحمدي", en: "Sharq Al Ahmadi" },
      { ar: "العقيلة", en: "Al Aqila" },
      { ar: "فهد الأحمد", en: "Fahd Al-Ahmad" },
      { ar: "فحيحيل", en: "Fahaheel" },
      { ar: "الفنطاس", en: "Al Fintas" },
      { ar: "هدية", en: "Hadiya" },
      { ar: "جابر العلي", en: "Jaber Al-Ali" },
      { ar: "المهبولة", en: "Mahboula" },
      { ar: "المنقف", en: "Mangaf" },
      { ar: "وسط الأحمدي", en: "Wasat Al Ahmadi" },
      { ar: "مينا عبدالله", en: "Mina Abdullah" },
      { ar: "الرقة", en: "Al Riqqa" },
      { ar: "صباح الأحمد السكنية", en: "Sabah Al-Ahmad Residential" },
      { ar: "صباح الاحمد", en: "Sabah Al-Ahmad" },
      { ar: "بنيدر", en: "Bnaider" },
      { ar: "جنوب الأحمدي", en: "South Ahmadi" },
      { ar: "جنوب الصباحية", en: "South Sabahiya" },
      { ar: "الصباحية", en: "Sabahiya" },
      { ar: "ام الهيمان", en: "Umm Al-Haiman" },
      { ar: "الوفرة السكنية", en: "Al Wafra" },
    ],
  },
  {
    title: {
      en: "Farwaniya",
      ar: "الفروانية",
    },
    areas: [
      { ar: "عباسية", en: "Abbasiya" },
      { ar: "ضاحية عبدالله المبارك", en: "Abdullah Al Mubarak" },
      { ar: "الشدادية", en: "Al Shadadiya" },
      { ar: "الرابية", en: "Al Rabia" },
      { ar: "الراي", en: "Al Rai" },
      { ar: "الرحاب", en: "Al Rehab" },
      { ar: "الأندلس", en: "Al Andalus" },
      { ar: "عارضية", en: "Ardiya" },
      { ar: "اشبيليا", en: "Ishbiliya" },
      { ar: "ضجيج", en: "Dajeej" },
      { ar: "الفروانية", en: "Farwaniya" },
      { ar: "الفردوس", en: "Al Ferdous" },
      { ar: "مطار الكويت الدولي", en: "Kuwait International Airport" },
      { ar: "أشبيلية", en: "Ishbiliya" },
      { ar: "جليب الشيوخ", en: "Jleeb Al Shuyoukh" },
      { ar: "خيطان", en: "Khaitan" },
      { ar: "مخيمات مباركيه", en: "Mubarakiya Camps" },
      { ar: "معسكرات المباركية", en: "Mubarakiya Camps" },
      { ar: "العمرية", en: "Omariya" },
      { ar: "الرقعي", en: "Riqee" },
      { ar: "صباح الناصر", en: "Sabah Al Nasser" },
      { ar: "جامعات صباح السالم", en: "Sabah Al-Salem Universities" },
      {
        ar: "مطار الشيخ سعد العبد الله",
        en: "Sheikh Saad Al-Abdullah Airport",
      },
      { ar: "جنوب عبدالله المبارك", en: "South Abdullah Al Mubarak" },
      { ar: "خيطان الجنوبي", en: "South Khaitan" },
      {
        ar: "غرب عبدالله المبارك الصباح",
        en: "West Abdullah Al Mubarak Al Sabah",
      },
    ],
  },
  {
    title: {
      en: "Jahra",
      ar: "الجهراء",
    },
    areas: [
      { ar: "الجهراء", en: "Al Jahra" },
      { ar: "نعيم", en: "Naeem" },
      { ar: "النسيم", en: "Al Naseem" },
      { ar: "شمال غرب الاجهرا", en: "Northwest Al Jahra" },
      { ar: "العيون", en: "Al Oyoun" },
      { ar: "القصر", en: "Al Qasr" },
      { ar: "روضتين", en: "Rawdatain" },
      { ar: "سعد العبدالله", en: "Saad Al Abdullah" },
      { ar: "الصليبية", en: "Sulaibiya" },
      { ar: "تيماء", en: "Taima" },
      { ar: "الواحة", en: "Al Waha" },
    ],
  },
];

export default kuwaitAreas;
