export const UPDATE_GOVERNORATES = "UPDATE_GOVERNORATES";
export const UPDATE_AREAS = "UPDATE_AREAS";
export const UPDATE_BLOCKS = "UPDATE_BLOCKS";
export const UPDATE_STREETS = "UPDATE_STREETS";
export const RESET_ALL = "RESET_ALL";
